# Configuration file for this exam
exam:
  year: 2025
  semester: 1
  name: Examen
  department:
    name: Département des Technologies Industrielles
    acronym: TIN
  course: Info1
  date: 2025-02-07T10:25:00+01:00
  duration: 100 # minutes
  type: examen
  school:
    name: Haute École d'Ingénierie et de Gestion du Canton de Vaud
    acronym: HEIG-VD
  orientations:
    - EAI
    - EEM
    - EN
    - ROCM
  faculty:
    name: Génie Électrique
    acronym: GE
  teachers:
    - Prof. Pierre Bressy
    - Prof. Yves Chevallier
    - Prof. Sara Grassi
    - Prof. Tony Maulaz
  teachers_not_in_charge:
    - Prof. Gregory Medwed
